# Generated by Django 4.2 on 2023-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('cert_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('issuing_org', models.CharField(max_length=200)),
                ('completion_date', models.DateField(null=True)),
                ('additional_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('institution_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=200)),
                ('field_study', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('comp_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('job_description', models.CharField(max_length=500)),
                ('manager_contact', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(max_length=200)),
                ('additional_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('organization', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
    ]
