# Generated by Django 4.1.5 on 2023-05-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=1000)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
