# Generated by Django 4.1.5 on 2023-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='entry_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
