# Generated by Django 4.1.5 on 2023-05-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_blog_created_on_alter_blog_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
